// .ai-memory/ — a DERIVED Obsidian vault over .planning/.
//
// .planning/ is the only writable truth. This module regenerates the vault, so
// it is always safe to delete. It is committed so a fresh clone can read the
// shared brain in Obsidian without running anything.
//
// Two hard rules:
//   Markdown only. Never copy graph.json, HTML, SVG, or any binary — that is
//   the "readable by Obsidian without binary clutter" requirement.
//   Deterministic output. Sorted traversal and LF endings, so a Windows
//   developer regenerating produces a byte-identical file to a macOS teammate.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { PKG_ROOT } from './platform.mjs';

const STAMP = '<!-- generated by comind; edit .planning/ instead -->';
// One vault section per source root. decisions/, discussions/, and research/
// used to collapse into a single `decisions/` directory, so two source files
// sharing a name silently overwrote each other and INDEX listed the same
// wikilink twice.
const DECISION_ROOTS = [
  { src: 'decisions', section: 'decisions', type: 'decision' },
  { src: 'discussions', section: 'discussions', type: 'discussion' },
  { src: 'research', section: 'research', type: 'research' },
];
const SECTIONS = ['phases', 'specs', 'graph', ...DECISION_ROOTS.map((r) => r.section)];

// Case-insensitive filesystems report one file under either spelling, so the
// prune set must compare the way the FILESYSTEM does, not the way the platform
// usually does: a Linux container on an APFS bind mount is case-insensitive,
// and a case-sensitive APFS volume on macOS is the mirror image. Probing the
// actual vault directory is the only answer that is right in both.
function foldsCase(dir) {
  try {
    const probe = path.join(dir, '.comind-case-probe');
    writeFileSync(probe, '');
    const insensitive = existsSync(path.join(dir, '.COMIND-CASE-PROBE'));
    rmSync(probe, { force: true });
    return insensitive;
  } catch {
    // Unwritable vault: fall back to the platform default. Folding is the
    // safer error — it can only make prune keep a note, never delete one.
    return process.platform === 'darwin' || process.platform === 'win32';
  }
}
const caseKey = (p, fold) => (fold ? path.resolve(p).toLowerCase() : path.resolve(p));

/**
 * Sorted directory listing — the basis of deterministic output.
 *
 * Plain .sort(), NOT localeCompare. This ordering decides the bytes of a
 * COMMITTED artifact: the order documents are inlined into a phase note, the
 * `documents:` array, and every INDEX row. localeCompare's collation is
 * ICU-dependent, so two teammates on different Node builds could generate
 * different vaults from identical sources and diff against each other forever.
 * Code-unit order is boring and identical everywhere, which is the requirement.
 */
function ls(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).sort();
}

/**
 * Is this a document meant for the SHARED brain?
 *
 * `.planning/**\/*.local.md` is in CoMind's own managed .gitignore block, under
 * the comment "Scratch notes a developer wants kept out of the shared brain" —
 * but the vault scanned for `.md` and republished them into `.ai-memory/`,
 * which the same block force-includes. Two consequences, both bad: content a
 * developer deliberately withheld got committed and became permanent in
 * history, and the vault stopped being a function of committed sources, so a
 * teammate's `comind sync` regenerated it differently and dirtied tracked files
 * — the one thing JOIN promises never happens.
 *
 * Filtering at the SCAN is required, not at the output: buildPhases inlines
 * each document's full body into the merged phase note, so a NOTES.local.md
 * leaks its text even though no note of its own is ever written.
 */
export function isSharedDoc(name) {
  const lower = String(name).toLowerCase();
  return lower.endsWith('.md') && !lower.endsWith('.local.md');
}

function isDir(p) {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function readIfExists(p) {
  try {
    return existsSync(p) && statSync(p).isFile() ? readFileSync(p, 'utf8') : null;
  } catch {
    return null;
  }
}

/** Slug → Obsidian-safe note name. Keeps wikilinks resolvable. */
function noteName(s) {
  return String(s)
    .replace(/\.md$/i, '')
    .replace(/[\\/:#^[\]|]/g, '-')
    .trim();
}

/**
 * Quote a YAML scalar when it would otherwise be misparsed.
 *
 * `title: Phase 3: Cleanup` is invalid YAML, and Obsidian rejects the WHOLE
 * properties block for the note — losing tags, type, and status. Titles come
 * from user H1s, so `: `, leading indicators, and edge whitespace all occur.
 */
function yamlScalar(v) {
  const s = String(v);
  const needsQuote =
    s === '' ||
    /^[\s]|[\s]$/.test(s) ||
    /: |:$|\s#/.test(s) ||
    /^[-?:,[\]{}#&*!|>'"%@`]/.test(s) ||
    /^(true|false|null|yes|no|on|off|~)$/i.test(s) ||
    // Numeric-looking values only need quoting when YAML would parse them to
    // something different ('1.0' -> 1, '07' -> 7). A plain integer stays a
    // plain integer, which is what a field like vaultSchema means.
    (/^[+-]?[\d.]+$/.test(s) && String(Number(s)) !== s);
  return needsQuote ? `'${s.replace(/'/g, "''")}'` : s;
}

function frontmatter(fields) {
  const lines = ['---'];
  for (const [k, v] of Object.entries(fields)) {
    if (v == null || v === '') continue;
    if (Array.isArray(v)) {
      if (!v.length) continue;
      lines.push(`${k}:`);
      for (const item of v) lines.push(`  - ${yamlScalar(item)}`);
    } else {
      lines.push(`${k}: ${yamlScalar(v)}`);
    }
  }
  lines.push('---');
  return lines.join('\n');
}

/**
 * Rewrite relative markdown links into Obsidian wikilinks so the graph view
 * actually connects. Leaves external URLs alone.
 */
function toWikilinks(body) {
  return body.replace(/\[([^\]]+)\]\((?!https?:|mailto:)([^)]+\.md)(?:#[^)]*)?\)/g, (_m, text, target) => {
    // Split on BOTH separators explicitly: path.basename is platform-dependent,
    // so a link written with backslashes produced a different wikilink (and
    // different committed bytes) on Windows than on POSIX.
    const name = noteName(String(target).split(/[\\/]/).pop());
    return name.toLowerCase() === String(text).toLowerCase() ? `[[${name}]]` : `[[${name}|${text}]]`;
  });
}

/** Extract a title: first H1, else the file name. */
function titleOf(body, fallback) {
  const m = body.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : fallback;
}

/**
 * Split a markdown body into a heading→content map.
 *
 * A line scan rather than one regex: JS has no `\Z`, and a `$` end-anchor under the
 * `m` flag matches every line end, so a lookahead-based split silently drops
 * whichever section happens to be last in the file.
 */
function splitByHeading(body) {
  const map = new Map();
  let current = null;
  let buf = [];
  const flush = () => {
    if (current && buf.join('\n').trim()) map.set(current, buf.join('\n').trim());
  };
  for (const line of body.split(/\r?\n/)) {
    const m = line.match(/^#{1,3}\s+(.+?)\s*$/);
    if (m) {
      flush();
      current = m[1].toLowerCase();
      buf = [];
    } else if (current) {
      buf.push(line);
    }
  }
  flush();
  return map;
}

/** Pull a `status:`-ish signal out of a GSD document without parsing all of it. */
function statusOf(body) {
  const m = body.match(/^\s*(?:\*\*)?status(?:\*\*)?\s*[::]\s*(?:\*\*)?\s*([A-Za-z][\w -]*)/im);
  return m ? m[1].trim().toLowerCase().replace(/\s+/g, '-') : null;
}

function writeNote(file, { fields, body }, written) {
  // Normalize to LF: source files checked out with CRLF would otherwise be
  // embedded verbatim, so the same .planning/ produced different bytes on
  // Windows and macOS — and the write-only-on-change guard never held.
  const normalized = toWikilinks(body).replace(/\r\n/g, '\n').trimEnd();
  const content = `${frontmatter(fields)}\n\n${STAMP}\n\n${normalized}\n`;
  mkdirSync(path.dirname(file), { recursive: true });
  // Only write on change so regeneration produces no mtime churn.
  const prev = readIfExists(file);
  if (prev !== content) writeFileSync(file, content, 'utf8');
  written.push(file);
}

// --- section builders -----------------------------------------------------

function buildSpecs(planning, vault, written) {
  const wanted = ['PROJECT.md', 'REQUIREMENTS.md', 'ROADMAP.md', 'STATE.md', 'CONTEXT.md'];
  const links = [];
  for (const name of wanted) {
    const body = readIfExists(path.join(planning, name));
    if (body == null) continue;
    const note = noteName(name);
    writeNote(
      path.join(vault, 'specs', `${note}.md`),
      {
        fields: {
          title: titleOf(body, note),
          source: `.planning/${name}`,
          type: 'spec',
          status: statusOf(body),
          tags: ['comind/spec'],
        },
        body,
      },
      written,
    );
    links.push(note);
  }
  return links;
}

function buildPhases(planning, vault, written) {
  const phasesDir = path.join(planning, 'phases');
  const out = [];
  for (const entry of ls(phasesDir)) {
    const dir = path.join(phasesDir, entry);
    if (!isDir(dir)) continue;

    // Merge the phase's markdown documents into one navigable note. A phase
    // spread across PLAN/SUMMARY/NOTES files reads as one thing in Obsidian.
    const docs = ls(dir).filter(isSharedDoc);
    if (!docs.length) continue;

    const parts = [];
    let status = null;
    for (const doc of docs) {
      const body = readIfExists(path.join(dir, doc));
      if (body == null) continue;
      status = status || statusOf(body);
      parts.push(`## ${noteName(doc)}\n\n${body.trim()}`);
    }
    const note = noteName(entry);
    writeNote(
      path.join(vault, 'phases', `${note}.md`),
      {
        fields: {
          title: note,
          phase: entry,
          source: `.planning/phases/${entry}/`,
          type: 'phase',
          status: status || 'unknown',
          documents: docs,
          tags: ['comind/phase'],
        },
        body: `# ${note}\n\nSpec source: \`.planning/phases/${entry}/\`\n\n${parts.join('\n\n---\n\n')}`,
      },
      written,
    );
    out.push({ note, entry, status: status || 'unknown', docs: docs.length });
  }
  return out;
}

/**
 * Graph notes from GRAPH_REPORT.md only — never graph.json or the HTML.
 * Sources are checked in priority order: GSD's .planning/graphs/ first, then a
 * standalone graphify-out/ for repos that ran /graphify directly.
 */
function buildGraph(repoRoot, planning, vault, written) {
  const candidates = [
    path.join(planning, 'graphs', 'GRAPH_REPORT.md'),
    path.join(repoRoot, 'graphify-out', 'GRAPH_REPORT.md'),
  ];
  const source = candidates.find((p) => readIfExists(p) != null);
  if (!source) return { present: false, notes: [] };

  const body = readIfExists(source);
  const rel = path.relative(repoRoot, source).split(path.sep).join('/');

  writeNote(
    path.join(vault, 'graph', 'GRAPH_REPORT.md'),
    {
      fields: {
        title: 'Knowledge Graph Report',
        source: rel,
        type: 'graph',
        tags: ['comind/graph'],
      },
      body,
    },
    written,
  );

  // Split the audit sections that are worth their own note and backlinks.
  const sections = splitByHeading(body);
  const notes = ['GRAPH_REPORT'];
  for (const heading of ['God Nodes', 'Surprising Connections', 'Suggested Questions']) {
    const content = sections.get(heading.toLowerCase());
    if (!content) continue;
    const note = noteName(heading);
    writeNote(
      path.join(vault, 'graph', `${note}.md`),
      {
        fields: { title: heading, source: rel, type: 'graph-section', tags: ['comind/graph'] },
        body: `# ${heading}\n\n${content.trim()}\n\nFull report: [[graph/GRAPH_REPORT|GRAPH_REPORT]]`,
      },
      written,
    );
    notes.push(note);
  }
  return { present: true, notes, source: rel };
}

/**
 * GSD keeps discussion output in a few places depending on version.
 *
 * Each source root gets its OWN vault section: flattening them into one
 * `decisions/` directory meant `decisions/api.md` and `research/api.md`
 * overwrote each other and INDEX listed `[[api]]` twice. Returns entries
 * carrying their section so INDEX can fully qualify the wikilinks.
 */
function buildDecisions(planning, vault, written) {
  const out = [];
  for (const { src, section, type } of DECISION_ROOTS) {
    const root = path.join(planning, src);
    if (!existsSync(root) || !isDir(root)) continue;
    for (const name of ls(root)) {
      if (!isSharedDoc(name)) continue;
      const body = readIfExists(path.join(root, name));
      if (body == null) continue;
      const note = noteName(name);
      writeNote(
        path.join(vault, section, `${note}.md`),
        {
          fields: {
            title: titleOf(body, note),
            source: `${path.relative(path.dirname(planning), path.join(root, name)).split(path.sep).join('/')}`,
            type,
            tags: [`comind/${type}`],
          },
          body,
        },
        written,
      );
      out.push({ note, section, type });
    }
  }
  return out;
}

function buildIndex(vault, { specs, phases, graph, decisions, versions }, written) {
  const lines = [`# CoMind Shared Brain`, ''];
  lines.push(
    'Derived view of `.planning/`. Every note here is generated — edit the source in',
    '`.planning/` and run `/comind-sync`.',
    '',
  );

  lines.push('## Active work', '');
  if (phases.length) {
    const open = phases.filter((p) => !/done|complete|shipped|archived/i.test(p.status));
    lines.push(`${phases.length} phase(s) on disk, ${open.length} not yet done.`, '');
    lines.push('| Phase | Status | Docs |', '| --- | --- | --- |');
    // The alias pipe must be escaped INSIDE a table cell: GFM and Obsidian
    // split cells on any unescaped '|', including one inside a wikilink, which
    // turned a 3-column row into 4 and dropped the Docs count.
    for (const p of phases) lines.push(`| [[phases/${p.note}\\|${p.note}]] | ${p.status} | ${p.docs} |`);
  } else {
    lines.push('No phases yet. Run `/gsd-workflow discuss` then `/gsd-workflow plan`.');
  }
  lines.push('');

  lines.push('## Specs', '');
  lines.push(
    specs.length
      ? specs.map((s) => `- [[specs/${s}|${s}]]`).join('\n')
      : '_No specs yet — run `/gsd-onboard`._',
  );
  lines.push('');

  lines.push('## Knowledge graph', '');
  if (graph.present) {
    lines.push(`Source: \`${graph.source}\``, '');
    lines.push(graph.notes.map((n) => `- [[graph/${n}|${n}]]`).join('\n'));
    lines.push('', 'Ask the graph instead of grepping: `/gsd-graphify query "<question>"`.');
  } else {
    lines.push('No graph built yet. Run `/comind-sync` (or `/gsd-graphify build`).');
  }
  lines.push('');

  // Every INDEX wikilink is folder-qualified, not just these: a phase and a
  // decision can both be named `api`, and Obsidian resolves a bare [[api]] by
  // a shortest-path heuristic that can point at the wrong note.
  for (const { section } of DECISION_ROOTS) {
    const rows = decisions.filter((d) => d.section === section);
    if (!rows.length) continue;
    lines.push(
      `## ${section[0].toUpperCase()}${section.slice(1)}`,
      '',
      rows.map((d) => `- [[${d.section}/${d.note}|${d.note}]]`).join('\n'),
      '',
    );
  }

  lines.push('## Contract', '');
  lines.push(
    `- Pinned tools: ${Object.entries(versions.tools)
      .map(([k, v]) => `${k} ${v.version}`)
      .join(' · ')}`,
    `- Vault schema: ${versions.vaultSchema} · generated by comind ${versions.comind}`,
    '- `.planning/` is writable truth. `.ai-memory/` is derived and safe to delete.',
    '- Bulk edits require an active phase in `.planning/phases/` — the gate hook enforces it.',
  );

  writeNote(
    path.join(vault, 'INDEX.md'),
    {
      // Deliberately no invocation-mode or timestamp field: this file is
      // committed, so anything reflecting HOW it was generated (init vs sync,
      // when, by whom) turns every teammate's regeneration into a spurious diff.
      fields: {
        title: 'CoMind Shared Brain',
        type: 'index',
        vaultSchema: versions.vaultSchema,
        comind: versions.comind,
        tags: ['comind/index'],
      },
      body: lines.join('\n'),
    },
    written,
  );
}

/**
 * The vault's own README, shipped from templates/ai-memory/README.md.
 *
 * It documents this directory for the humans who open it in Obsidian, and was
 * previously written but never installed anywhere — dead documentation.
 * Stamped like every other generated note so the prune step owns it.
 */
function writeVaultReadme(vault, written) {
  const src = path.join(PKG_ROOT, 'templates', 'ai-memory', 'README.md');
  const body = readIfExists(src);
  if (body == null) return;
  writeNote(
    path.join(vault, 'README.md'),
    {
      fields: { title: '.ai-memory — the shared brain', type: 'vault-readme', tags: ['comind/index'] },
      body,
    },
    written,
  );
}

/** Minimal shared Obsidian config so the vault opens the same way for everyone. */
function writeObsidianConfig(vault, written) {
  const dir = path.join(vault, '.obsidian');
  mkdirSync(dir, { recursive: true });
  const app = {
    alwaysUpdateLinks: true,
    newLinkFormat: 'shortest',
    useMarkdownLinks: false,
    attachmentFolderPath: './',
    strictLineBreaks: false,
  };
  const file = path.join(dir, 'app.json');
  const content = `${JSON.stringify(app, null, 2)}\n`;
  if (readIfExists(file) !== content) writeFileSync(file, content, 'utf8');
  written.push(file);
}

/**
 * Regenerate the whole vault.
 * Returns { ok, written, removed, stats } — never throws on a missing .planning.
 */
// No `mode` option: init and sync produce the SAME vault by design. It was
// threaded down to buildIndex and never read, because recording how a committed
// file was generated turns every teammate's regeneration into a spurious diff.
export function generateVault(repoRoot, versions, { dryRun = false } = {}) {
  const planning = path.join(repoRoot, '.planning');
  const vault = path.join(repoRoot, '.ai-memory');

  if (!existsSync(planning)) {
    return {
      ok: false,
      reason: '.planning/ not found — run /gsd-onboard (or /gsd-new-project) first.',
      written: [],
      removed: [],
    };
  }
  if (dryRun) {
    return { ok: true, dryRun: true, written: [], removed: [], stats: { note: 'would regenerate .ai-memory/' } };
  }

  const written = [];
  for (const s of SECTIONS) mkdirSync(path.join(vault, s), { recursive: true });

  const specs = buildSpecs(planning, vault, written);
  const phases = buildPhases(planning, vault, written);
  const graph = buildGraph(repoRoot, planning, vault, written);
  const decisions = buildDecisions(planning, vault, written);
  buildIndex(vault, { specs, phases, graph, decisions, versions }, written);
  writeVaultReadme(vault, written);
  writeObsidianConfig(vault, written);

  // Prune notes whose source disappeared, so a deleted phase does not linger
  // in the shared brain as a stale note.
  const fold = foldsCase(vault);
  const keep = new Set(written.map((f) => caseKey(f, fold)));
  const removed = [];
  // '' is the vault root: a stamped note there (a README from an older layout,
  // or one a user dropped in) was never pruned, so it documented a layout that
  // no longer exists, forever.
  for (const section of ['', ...SECTIONS]) {
    const dir = section ? path.join(vault, section) : vault;
    for (const name of ls(dir)) {
      const abs = path.resolve(dir, name);
      if (isDir(abs) || keep.has(caseKey(abs, fold))) continue;
      const body = readIfExists(abs);
      // Only ever delete files we generated. A hand-added note is left alone.
      if (body && body.includes(STAMP)) {
        rmSync(abs, { force: true });
        removed.push(abs);
      }
    }
  }

  return {
    ok: true,
    written,
    removed,
    stats: {
      specs: specs.length,
      phases: phases.length,
      graph: graph.present,
      decisions: decisions.length,
      notes: written.length,
    },
  };
}
